export const ascii = `                                                                                                                                                                                                    
                                                                                                                                                                                                        
                                                                                                                                                                                                        
                                           .+qdqm:                                                                                                                                                      
                                         +#Wdwmwb@@:                                                                          =qbhahdm                                                                  
                                       :@*:    ..-@@                                                               -mmp@@@@@@W+   -wb@@oq-                                                              
                                      -@q     .:=-b@                                                         :wkho@@ko@@@@@@*-:   :=wbW@@@@@@hp=                                                        
                                     :@q      .-m:@@                                                     :+b&hbdbo@@@@@@@@@@@d+mwqpbhW@@@@@@@@@@@p:                                                     
                                     #o      .:m=w@=                                                 .wkW@#@@@@*ohhhaoM#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@m                                                  
                                    -@=     .:=w:@a                                                +*@o*Mokqm-:...::::::::=mqb*@@@@@@@@@@@@**@@@@@@@@@@d.                                               
                                    d@    ..:-w-d@.                                             :d@@@km-.   :-=+++++++++++=-------::-mb@@@@@#@@@@@@@@@@@@d.                                             
                                    oa ....:-+q-@k                                            -o@@p-   .-+mm+++====----===++++mmmmm+=:::m*@@@@@@@*@@@@@@Md#h                                            
                                    @b ..::-=m+m@-                                          =@@d-  .-+mm++=-::....      ...:::---==++mm=..=a@@@@@@@@@@@@@@b@@+                                          
                          -doMMop-  @d.:::-=+q-b@                                         =@@m   -mm+=--:.                      .::--=+mw+..m@@@@@@*M@@@@@o#dMk                                         
                        =@a+:..-w*@w@k----=+wd:@@                                       :M@+  :=++=-:.                       .-:.  .:--==mm-.=a@@@@@&@@@@*@@@+b@.                                       
                       m@=     .:=d@@a=++++mqd:@b                                     .h@m  -+=-::.                        :@@@@@@q:  :--=+m=.-b@@@@@@@@@@@@kaqw@-                                      
                   :+mq@w     .::+pd@@mmmmwqdd-@q                                    w@p  -+=-+k@@@d                       d@@@@@@@@p. .:-=+m+.:b@@@@@@@@@&@@@@+d@:                                     
                 +@Mpmh@-  :dohaahah@@hhhhbdbd=@m                                  .@W. :+m=p@@@@@@@:                       +pa@@@@@@@:  :-==mm.-a@@@@@o@@Ma@@@W+w@-                                    
                q@=   q@+-=@@:  .=mb@kpqpk@@@d=@+                                 m@q  +m+m@@@@@@@b:                             -p@@@@.  :-=+mm =W@@@@@@@@@@@@@=pm@.                                   
                @b    w@b+b@-      .w     .=a@h@-                                h@: -++-m@@@km:                                    =*@w   :-=+w+ m@@@@@#a@@@#b@&@d@a                                   
              +h@p   .-M*qa@=::.::-+-...::::.=@@+        -+wwm+:               .@a  ++=- :w:                                          .     :=++q-.d@@@@@@@@o@@@@@m-Md                                  
            =@b-@W.:::-q*kh@o++-----:::----=++:k@=       .:=+wqqw=            =@q .m+=:                                                      -=+mw.=@@@@@@@@@M@@+Mop-@+                                 
            @b  w@d==++wkaa@@awwwm++++++++==+mq.d@-                          m@+ -w+=:                                     -mpbbpm-          .-++q+ p@@@@*@@*h@@kb@h+q@                                 
            @q .:d@*wmqbho*#@@@Mbppppppdbm==+mqq W@                         p@- -m+=:  :q#@@@@@d.                       =&@@@@@@@@@@k-        :=+wd.=W@@@@@@@@@@o@W==+@-                                
            q@---=p#@@kpdbhaa*&@@@@@@@@km==+mwqd-:@m                       b@: -m=-: =&@@@apwqb@@p                    :@@@d+-...:+b@@@W:       -+mp-.b@@@@@oa@*a=b@qpmkW                                
             h@dqpdbh@@@@@@@@@@@@@#kdw+-==++mwqdm @h                      k@. =m==..d@@*=   .:--=od                  +@a-     :--: .m@@@m      .=+mm m@@@@@@*@@@a@@k@m *b                               
              q@@kdbhaahko@@@@@@@hm=----=++mwqpp+ @o                     h@. +m==..h@@m   ma@@@@@dk-                +@=    -d@@@@@@*+:d@@m      -+mw:-@@@@@@@@@o@@@#@d:.@.                              
                q@@Wakko@@@p+mq@@+=====++mmwqpdq. @p                    k@. +m=-: q@@-      =@@@@@@k               :@:        p@@@@@@@-q@@.     :++w-.o@@@@@@@@@@@a@@p= @w                              
                  *@@@@Mhw=::-+@kmm++++mmwqpddq= w@.                   b@. =m=-...@@w  =-   .@@@@@@@               b+   =.    -@@@@@@@@-W@d     :=+w+ b@@@@@@@M@h@@@M*d:@h                              
                  =@bw+--:::--+@kqqwwwwqqpdbbp- :@q                   d@: =m=-.  -@@   @*w=p@@@@@@@@               k   .@h-..+@@@@@@@o@b=@@     .=+wm p@@@@M*@@@b@@@a@p+:@.                             
                   @@mm+=====+mbWdddddddbbkkp- :@b                   q@- =w=-:   -@h  :@b@@@@@@@@@@k              :m   q@p*@@@@@@@@@@b@#.@@     .=+mw q@@@@@@@h#@@@@@a.b @d                             
                   .@@mwqwmmmwqpaakhhhhhhhbw. +@@o                  p@- =w+-:.   .@b  .@ph@@@@@@@@dm              .=   d#ma@@@@@@@@@@q&b.@k     .==mw w@@@@@@@#@@@*m-@d+.ad                             
                     @@dmwpddbbkhahbdbbdqm-:+W@Mw@b                p@- -w+-:.     ko   oawW@@@@@==w                :   =@ww@@@@@@@@h+p&:=@:     .=+mw m@@@@@o=@@b@@q:@@:=@p                             
                      m@@hqwqqpppppddpqwwqbM@*aod+@k              d@- =w+=:.       W:   howwpdpm+m                      o#mmM@@@@q -qb- hq      .=+mw m@@@@@@*@@#@@a@@pMw=@+                            
                        :p*@&*oaoW&@@Mooaaahhhaa*d-@o            d@- =q+-:.        =q:   -pqwm+=.                        qd+==mmm+qd+  mq       .=+mw m@@@@@@@oh@@@@*@k=m p@                            
                             .::-h@@dkahhhhhhhaaoMd-*@.         b@- =w+-:                                                     .-++-. .==         =+mw m@@@@@@@aq#@oo=a@mm b@                            
                                  :@@kdhhhhhhhhaaa*h-p@+       h@-.+w=-:.     :-----.                                  mpq=                     .=+mw m@@@@@p@@o@@@hm@a@- @q                            
                                    m@@dbhhhhhhhaaaoo++@o     #@:.+w=-:.    :+++++====:   :d@m                        :p@@bq       :-----:.     .++mw m@@@@@k@@@a@@@@h-+omm@-                           
                                      d@*pbhhhaaaaaooMd=k@m  @@. +w=-:.     .+++++====:   :.+Mw:                 .-mk@@@@@      .-=====+++++-   .++mm q@@@@@@*@@@Wpp@h+mop m@                           
                                       .*@kpkaaaaaaaoo*oqq@*@k .mw=-..        .:---:.        d@@@@Mhbpqwmmwqda@@@@@@@@@@@m      :======++++++.  .++wm w@@@@@@o@@@aqq@@o@::+:@                           
                                         =@@pqkoaaaoooo*Mh@@q :mm=-..                        .@@@@@@@@@@@@@@@@@@@@@@@@@@a        .-==+++++=-.   .++w+.q@@@ha@@aq@@@@h#b@++.*h                           
                                           m@@qqkaaaoooo*@@= :wm=-.                           :@@@@@@@@@@@@@@*hkkkkkbb@h                        .+mw=.q@@@@@@@*p@@Mb.@@@@m do                           
                                             w@MwwboaaaM@@. =q+=-.                             .@@@@@@@@@Wkbdddppqwwb@w                         :+mq=:p@@@@@km@#d@@ab@=dMm -@                           
                                               p@Wqqkh#@h  +w+-:                                 p@@@@@*dpqwm+====wob.                          :+mw-:d@@@@@#W@q-@@b&@W@w.:wW                           
                                                 p@Mq@@q .ww+-:                                   .p@@@dqm====+qk*d:                           .:+mw:-b@@@@@@@@#@@@o@@php -+@                           
                                                   q@@= -qm=-.                                       -wdkhkhhkdw-                              .-+mw.=h@@@Mpd@d@@Mma@b+:@d -@.                          
                                                   k@: =qm=-.                                                                                  .=+mw =o@@@@*@@W@@@+h@hmm@-. @+                          
                                                  @@. +q++:.                                                                                   :++wm +&@@@@@#d@@p@@@@@@@b:: oa                          
                                                .@M .mq+=:                        :+qdhoMW#M*abpm-.                                            :+mq+.w@@@@@@hb@o=@@kk-@@b+: @q                          
                                               :@h .ww+=:                    -wkM*kpwm++++mmwqpba@@@aw:                                        -+mp-:d@@@@@@@&@@@@@bp=@@q@w p@                          
                                              :@k .ww+=:                 .mo&km-...-=+mmwqdkhhhaaoah*@@@b-                                    .-+md:-h@@@h@@Wd@@@@@@M@hMwdq  @+                         
                                             .@h .wwm=:.               +oWp-    .-+=++mmqdkbdb*@@@@@@@@@@@@m                                   =+wd:=#@@@@@@@@M@@@o@@o:p@.-.+@                          
                                             @& .wwm=:              .d@d:          --=+qqwwqdookh@@@@@@@@**@@m                               ..+mwp.+@@@@@oW@@@@@@@@@*w@o:- @q                          
                                            @@..mqm=:.             b@q  .--        :-+m+=+mphbdb@@#@@@@@@@@b*@@-                             ..mmqq.m@@@@@@@@b=..:+d@@@@@pw =@                          
                                           o@:.mq++:.            m@d  -++-         :=:--=mpdqqbWohoW@@@@@@@@hd@@q                             :mmqm.w@@@@@@@*-:.    .:mk@@*+.@=                         
                                          q@= =pm+-.           .&@-.=+qm-.        -:.:--+qwmwbobbha@@@@@@@@@@oq@@k.                          .:mmp+:p@@@@@@@*m=-::..  ...=qo@@a                         
                                         :@d :qm+-.           =@b +pwpm----    ..-..:--mw++wkbpdbk#@&@@@@@@@@@aq@@h:          .=             .-mwp--h@@@@@@@@apwm+=-::...:.:-+dWom.                     
                                         M@ .mq+-:.          m@q.dhpbm===m=-:::-+..---mm++qhqqpdo*M*W@@@@@@@@@@bw@@p=.        .:             .+mwp.=@@@@@@@@@@@hdpqwm+=--:::--:-+pWMw.                  
                                        +@= -p++:.          m@q-oodhw+++q+++--=w--=-=++=+qbwqpdMMaoo@@@@@@@@@@@@wp@@m=:    -=   .+:         .:+mqw.m@@@@@@@@@@@@@Mbppqqwm+=----==--=p&*m                
                                        @h :pw+-..         -@d=M@bopmmmd+mm=-=q==+=++=+mbbpppdWohao@@@@@@@@@@@@@b+#@a==.         -.         .-mmq=.d@@@@@@@@@@@@@@@@@hdpppqm+====+++=-=d@d.             
                                       m@:.=dm+:.         .@&=M@hobqqwdmmq+++p++++m++mmphhbpd#akao@@@@@@@@@@@@@@h+q@@+==.    m-            ..=wwp:-h@@@a@@b@@@&d@@@d@@@@odpppqm++=++mww=:w@b            
                                       @h -qwm-..         h@+o@*a*qpqdqwdmm+qm+mmwqwmwwqddpbMhkha@@@@@@@@@@@@@@Mh++@@p==-                 ..:+mwq.+@@@@@@@M@@@@@@@hm@@@@@@@&bpppqw+++mqdd= a@.          
                                      +@-.+dm+:.         -@hd@&a@bdpdbwdqwwwwwwmqpqqqqqbdpkMhhha@@@@@@@@@@@@@@@ohm=M@h===.                ..:mmq+.w@@@@do@@oh=@@@@@@@#k@p++w@@@Mpm=+mwqdbam @h          
                                      a@ :qq+=..         h@w@@##*bbdkpbdqqqqdqwpbqqppphbdaWhaaa@@@@@@@@@@@@@@@@hh+=k@M++=-               ..:-mwq:-b@@@@b@@@apw@@m@@Mm@@hwkph@bm---=+mqpbhab k@          
                                      @d -dm+:.          @@p@@W@akbbbbhppppkdpqhdddddakbM#hao*@@@@@@@@@@@@@@@@@ho+-d@W++==               ..:+mqw.+@@@@@@@o@@@@@op@@Mb@@@@hw-.:--=++mqpbhoh-.@q          
                                     -@+.+dm+:.         -@hb@@&@oahkbobdddkkddhkbhbbhak&#ao*#@@@@@@@@@@@@@@@@@#ok=-d@*++==:              .:-wwp=.q@@@@@@@@@@@@@@@@@@Md+:. .::--=+mwqdkaok- @#           
                                     w@::wpw+..         +@do@@@@M*ohaahkkhMkkkok@hkkhh@#oMM@@@@@@@@@@@@@@@@@@@a@w=:a@h++==-             ..:+wqp:-a@@@@@@@h@@@@@#d+:    ..::---=+mwpbhood..@#            
                                     k@::qqw=..         m@pM@@@@@@MM@oooa@Maaah@Mhaao@@M##@@@@@@@@@@@@@@@@@@@W*k+-:@@p+++=-            ..:-mwpm.+@@@@@@@@@@@b+.     ...:::--=+mwqdho*k+ m@d             
                                     M@:-pqw=..         m@bo@@@@@@@@@WM*@@W**oW@a***@@W@@@@@@@@@@@@@@@@@@@@@@h@m-.+@@w+++==            ..:+wwp-:d@@@@@@@@h=        ...::--=+mwqdho*hm -@@-              
                                     @@:-dqw-:.         =@ab@@@@@@@@@@@@@@@##W@@@@#@@@@@@@@@@@@@@@@@@@@@@@@@a@q=: h@hm+++==           ..:-wwqq.+@@@@@@@h:         ..::--=+mwqdho*bm.-o@+                
                                     @@--dqw=:.         .@@q@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@h@d=- -@@q+++++-           .::+wqd=:p@@@@@@m .        ..::-=+mwqdkaad=.+M@m                  
                                     @@+:dqw=:.          h@q@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@k@b=-. *@am+++++:          ..:=wwdw:+@@@@@@w.:.      ..::--=+mqpbhbm::q&h-                    
                                     *@q:dpw+:.          :@#q@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@&b@b=-. p@@wm++++=.         ..:-mwpd--d@@@@@@-::........::--=+wqdbp=:mo&q                       
                                     d@b-qdwm::           b@ph@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ob@p=-. m@@qm+++++-         ..:-mwqb+.m@@@@@@W=-:::...:::--=++wqdkm=b@@:                         
                                     =@*++bww::.           @@m@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ha#w=:. +@@pmm+++++.         .::+qqbp.=#@@@@@@o=--:::::::--=+mwqdkaa::@q                          
                                      @@q-bqw=:.   :. -.   :@@w@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@*h@h+=:  m@@qm++++++-         ..:=qqpd-:b@@@@@@@b+=--------==+mwqdkha= b@dqw=                       
                                      @@a-wbwm-:.  -: ..    -@@pW@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@*hooq+-. .b@@wm++++++=         ..:=qqdb+:q@@@@@@@@bm+===--===+mwqpbkhp::@@@hdph@w                     
                                      m@@m=hqq=:.    :       .&@kh@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ohbbp+=:  =@@hmmm+++++=         ..:=qpdbm:w@@@@@@@@@hqwm+++++++mwpdbhb=:d@@@@#kdw=@b                    
                                       @@b=qbqm-:.   -: =      d@@b*@@@@@@@@@@@@@@@@@@@@@@@@@@akbpw+=-. -h@@pmmm+++++=         .::=qqdbw:m@@@@@@@@@@@dpqwmmmmmwqpbkbm-p@@q==w@@hd+-@.                   
                                       w@@q=bbwm-:.             =@@@oW@@@@@@@@@@@@@@@@@@@@@#okbpwm+-:.+a@@bmmm++++++=         .::+qpbbw-m@@@@@@@@@@@@Mbdpqqwqqqddbpqb@@kpdbhq:@@d::@.                   
                                        @@*+wadq+-:.             :b@@@WoW&@@@@@@@@@@@##@Wohkdpwm=-:-q@@@kwmmm++++++:         .::+qpbbw-m@@@@@@@d@@@@@@#kbbddddddbbkhkabddbbhk.pM: ok                    
                                        :@@k=padp+-:.             .+d#@@@Waa*ahaaaaahhhkbdqwm+==md@@@Mpmmmm++++++=.        ..:-mpdbbm-q@@@@@@@*@@@@#@@@@Mhkkkkkkbkbbbbbbbbbbm.-. h*                     
                                         w@@d=dhdq+-:.              =mwdW@@@@@akbdppqqqwwmwqba@@@@odwmmmmm+++++=:         ..-+qddbb=-d@@@@@@@@@@@@@@@@@@@@@obdbkhhkkkbbbbdq=.  w@q                      
                                          k@@d=bhdpm=-.              :+mmwqbo@@@@@@@@@@@@@@@@Mhdqwmmmmmm++++++:         ..:-mpddbp-=b@@@@@@@#kq@@@WM@ok@@@@@@@kqm++mmmmm+-..=d@h.                       
                                           a@@p+dhbdw=-:.              -mmmmmmwwqpddbbbddpqwmmmmmmmmmm+++++=:         ..:-+qpdbbm-wo@@@@@kk@@@@@@@W@@@@@Mdd@@@h@@@@ohkkkhoWMk+                          
                                            k@@bmpakdq+-:.        ..     -+mmmmmmmmmmmmmmmmmmmmmmmmmm++++-.         ..:-=wpdbkq==b@@@@@@*h@@@@@b+@@@b@@akq*bMq.: h@==+++-.                              
                                             p@@a+whabpw=-:.      .:       .-=mmmmmmmmmmmmmmmmm++++++=-.         ..::-+mpdbhb+-wM@@@@@@@@@@@@od+*@op:@@@aWbwd-  ph                                      
                                              +@@@w+bohbpm=-:..m+ -            .-=++mmmmmmmmm++==-:.           ..::-+wpdbkkw=+k@@@@@@W@@@@@@@@@@@@dq@@&b=mk=:q=ow                                       
                                               .@@@b+wkohbq+=---..=.                 .::::....             ...::-=+qpdbhkq=+d@@@@@@@@@@@*@@@@@a@@@@@@@&qdp- +@h.                                        
                                                 q@@@dmqkahbpw+--:.                                     ..:::--+wpdbkhbq++d@@@@@@@@@o@@@W@@&hqW@@@@k-w*pq. :@=                                          
                                                  .o@@@dmqbahbdqm+--:...                          .....::--=+wpbkhhhdw+mk@@@@@@@@@@oo@@@@@@@W@@m#@b+mh-. .pb                                            
                                                    -#@@&dwwphhkbdqw+=--::....       .  ..........:::-=+mwpbkkkhhbq++qo@@@@@@@@@@#@@@@@@ok@@*pmh@@opq: :ho-                                             
                                                      =@@@@hqmqdkkkbdpqwm+=---::::.....::::::---==++mqpdbkkhahkpmmqk@@@@@@@@@@@@hd@@@##hqd@@@*@Wkk=. :h#=                                               
                                                        w&@@@@kqwqpbkkkbbdppqwmm++++=+++++++mmwqpdbbkkhhaahdqwmqh@@@@@@@@@@@o@@@@@@@@@@M@@@Mw=@m:  -b@+                                                 
                                                          .d@@@@@hpwwwqdbkkkkkbbbdddddddbbbbbbbkkhaaahbpqmmqdW@@@@@@@@@@@@@@@@@&kk@@@Mqk@@h+:qm  m@a=                                                   
                                                            .p@@@@@@@hdwmmmwqpdbbkkhhhhaahhhhhkbbpqwmmwqbM@@@@@@@@@&@@#@@@@@@@@@@@#kqqkWdww--..m*d.                                                     
                                                               .h@@@@@@@@@*hdpqwwmmmmmmmmmmmmmwwqpdk*@@@@@@@@@@@@@@@@@@@@@@@@@@@@@obWhm:  :=pah+                                                        
                                                                 .=+M@@@@@@@@@@@@@&M*oooo*#@@@@@@@@@@@@@@@@@@@@#@@@@Mbh@@@@@odmk@*bq+. :mkMk+                                                           
                                                                     mh##@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@M*aa@@@**#@kd@@@Mkpp=..:=p*op-                                                              
                                                                        ..=M@@@@@@@W@@@@@@@@@@@@@@@@@@@@@@&M@@@oh@@@hbqphdm+-..-md*@op=.                                                                
                                                         ........::::::::::-=md*@@@@@@@*ohb@@@*haho@@@@@#*hbbhhdqwqdqwm+--+wk@@@*bw+======-------:::::::..........                                      
                                                   .....:::::-----=========+===+mwpdba#@@@@@okbk@@hbqmmwmmwqddppdkkdk#@@@@&obpwm++++++++++=====--------::::::::........                                 
                                                         .....::::---------========+++mmwqqbhoMMoo#@@@@@@@@#oaoakbbbdpwwm+++++++======---------:::::::::........                                        
                                                                             .............::::::::---------::::::::::::::.................                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
`;
