export const ascii = `                                                                                                                                                                                              
                                                                                                                                                                                                        
                                                                     =wbo%@@@@@@@@@@@@@@op=                                                                                                             
                                                                -p*@@Wadww+mmmmmqddppppbh*#@@@p:                                                                                                        
                                                             +M@hm+mm==..=--+mmmwwqppbhhkkdpqd%@*kq:                                                                                                    
                                                          .h@@w:.+wqm======-==+mmmwwqqppho%@@@@p+=p@@b-                                                                                                 
                                                        :%@d+-+mdhkbbkkhha**hbpwmmmwwqqpbh*W@@@@@%mwwq*@q                                                                                               
                                                       *@p:-mpbbpqqqqqwwwmmmwqpa%*dqwwqqdka#@@@@@@@@@b==@@m                      =wqqm-                                                                 
                                                     +@Wmwpdppqwmm+==----==++wwm+wb@*pwwpkdbk*@@@%@@@@@h+q@@o                 +w+-.:-+d@k                                                               
                                                    h@pqdw+mm+--:::......:-----=mqqmw*@hqqpbha@@@@@@@@@@Wq+d@@h:           -q=       ...M@                                                              
                                                   M@dpm+m=--:.               .----mqqwo@*qwph%@@@@@*hk@@@*kp==@@         dw:.:::...:-+.-@:                                                             
                                                  M@ammq=:.                      .==-=ppwa@*pdo@@@@@@@@@@@@@@@: @@m       .:=wpbdq+==-::@h                                                              
                                                 k@h+p+-.                          .-=:-ppw*@oba@@Wak@@@@@a@@@%dq+p@m            =pkhahd:                                                               
                                                +@k=d--                              .-=--dpw@@ahMMM@@@MW@@@@@@@@W=:@@.                                                                                 
                                               =@*=p:-                                 .-=:=hqp@@hkahk@@*ho@@@@abW@mmq@%-                                                                               
                                               @@=b.-                                    .--:qkmh@@*@W@@@@@@@@@@@@@@@p =@d                                                                              
                                              =@mp:-                                       :=--dpw@@@@@@@@@@@@@@@@@od%# +@b            .:-==-:.                                                         
                                              W#=w.                                          -=:+kwd@@@@@%W%@@Whh@@@Ww@@m.@@   .-=+=-:                                                                  
                     q@@aaW@a-               +@+d:-                    .:                     .=-:qbw@@@@@@@@@@@M@@@@@@@@.:@@q       .:-::.                                                             
                    @@.     =M@+             *@=q.                    p@@@Wq=::::-=-.           -=.=hwp@@@@@WW@@@@@@@@@@@aw-.d@w  ..         ..                                                         
                   *@        .+@@            @kq=:                    =@@@@@@@@@@@@@q            :=-.pkm#@@@@@%a@@@@@@@@@@@@d -@d           .                                                           
                   @@       ...-k@+          @wd:.                      mh@@@@@@*p=               .-=.=oqp@@@@@@@@@@@@@*M@@@@= q@@-               ...                                                   
                   q@. .   ....:+p@m        q@+k         =q-                                        :=:.bbm#@@@@@@@@@@@@od@@#%h= =@h     :--=-:         .:---:.                                         
                    q@+      . -mmq@+       @@=b        q@@@=                  :q*#WMMMhw.           :--.+hwd@@@@@Wkha@@@@@@Mqa@a -@@           -+ww+-.                                                 
                      pokpm++==mwwmq@.      @@md       +@@@@.                +@@m      :p@@+       -  +m+-:pkwW@@@@@@%h@@@@@@#m@@m @@@:   -mqq+:       .:::.                                            
                         .=mwqpdkookk#      @bwq     -*@@@#.                *@.  w%@%k+   +@@      w   @=-=.=aqp@@@@@@@@@@@@@@@@@Wq-:p@@p       .-=+=:       .-=-:.                                     
                                    .       @mp=   +@@@@*=                 a@     b@@@@@+   *@      qqda. :=-.pkw*@@@@@@@@@@@@@@MdoWb: d@a.  ::.      :=+=-.                                            
                                            @-k.   mpm-                   -@      =@@@@@@=   @*            .-+.-aqp@@@@@@M*@@#k@@@h*@@q. w@b    -mqm=.                                                  
                      :-::                 .@:k        .wbkbp+.           m@      @@@@@@@k   w@              :==.pkmo@@@@@@a@@@b@@@@@@@@d  @@         .::-.                                             
                  d@@apwmwdaWobw:          a@.p      -@o=   .=hW=         =@  @@@@@@@@k@@+   =@               .-+:=aqq@@@@@@@@@@@@@@@@@@@p =@@   .-:.       .:--:                                       
                p@p        .=+mqdbd+       @@:w     w@.  q*ap:  ha         @w -@@@@@@@d%w    d@                 :+-.pbm@@@@*@@@@@@@@@MdqMa. =@@:      :---.                                             
               m@-          :===+qdm       @a:+    =@     @@@@@  dd         @+  +o@@@om    -q%p+=.               :==.=*wh@@@*@@@Maa@@@@ow@Wq. +@p           ..                                          
               h@          .:-mhk-         @h-=    @d     @@@@@a  @          db          mw-                      .-=::app@@@@@@@@*h@@@@@@@@#d  @a   .:.........                                        
               -@+   .... .:mWa.           @k==    @m w-=o@@@@@@  k.           mq+:   .+a- .  .-:=mqm        :      :=-.bbw@@@@@@@@@@@@@@@@@%*p M@q  .:-==-:... :-=:.                                   
                -@d.     -p@h.             @b+-    @h b@@@@@@+@w  o                ..:.      :d    :w@=      h      .:=+.whw@@@@M*@@@@@@@@@@@@b  w@b.    .-+m+=:       ...                              
                  +kaaaook+               +@pm-    -@  p@@@@@W=  -q      .=pW@@@@a=           qk   . =%  .+mq:        :=m.+%m@@@@@@@@@@@@ha@#aahd. @*.-=-.      :=+-                                    
                                          .@qq:     =@-  .=-    -p   -wa@@@@@@@@@@@q           -km::=h:                :=+.+@m@@@@@@@@@@@@#@@k=*@k :@h   .-+m+-                                         
                                           @wp..      ha-     -m-  q@@@@@@@@*pmmwh*              .--.             .::   :-=:+M+@@@@@@Ma@@@@@@@p*@h  d@q .       :=+==:                                  
                                           @mb..      .dq=:-=+.   .@@@@@@@adw++-:                              -kq--=qk= ::--=*+@@@@@@Mh@@Mh@@@@@@k- q@-  .+wwm=-...                                    
                                          :@=k .                   +M@@*q=:                                   ok     =p@m ::+-maw@@@@@@@@@@#b@@ab@@a: @@ .:..:--:.       ..:...       ...               
                                          +@-k :      ...                    .-mpbaMWMoakdqm-.              w@-     .qkb@-.-.+.ddp@@@@@@@@@@W@@@kw@@- @@  ...    -+wqw+:     .::::.                     
                                          w@-k :    -+ :kp               =b%@*bw+=---=mpbaM@@@@*q-        mWw      .+kh=@w..: =.Ww*@@@@@@@@@@@@@@qa@. W@:  .=wqq+:      -++=:                           
                                          k@:k :   =m   -@            +*@d=      .:-+wdkao**oaaM@@@a+  :p#m     ...mk*++@w. :..=:@+@*@@@@@@@@@@@@k@@k. d@: .    .=wppq+:                                
                                        .W@@:h :   b:   ma          p@k.        :=+qdbka*W@@@@@@@*a@@@@W=      ..-qo*q @bm. .- =.pbk@%@@@@@@@Wh@@@@@#k. @@  +dkdm:                                      
                                       d* b@-h :   .k=-mb         w@b          -+mwpkaooMW%@@@@@@@@@Wm       .::mk*ow o@m+.  .: +.@q@W@@@@@@@@Wb@@kp@Wp q@+          .                                  
                                     +@m  p@=b :     .:.         @@          :-=+mwpbaoo**@%@@@@@*+       ...:+boab: *@mm-.   : =:pka@%@@@k*@@@a@@@pd@m @@                                              
                                   -@p   :p@md.:               :@b       -mwqpppqqqpdbkha@@@@Mq.       ....-wh*ad= .@o++=-    .: +-@w@h@@@@a@@@@@@@qd*. @@   .-:.         .::.                          
                                 -*d    :=b@pq:-              :@q     moaq-..:-+mqpba*@@@km.       ....:-+daohp=  b@w=+=-      : m:*q@*@@@@@@@@@a%@%@Wd =@m        -+wqm-                               
                               +*q     :+dh@am=:              @b    q@m               :++     ......:=mdaMobw: .k%= :=--   -   . --qbh@*@@@@@@@@Mw@@@@h. @@   :mwm=:         .:..                       
                            -ba+    ..=wdbp@@=q:             k@    @k                    ...::::-=mqk**abw-  +*%m      -   d    ..+=Mp@h@@@@#@@@Wq@@@Mp  @@          :+wwm-.                            
               =qdkbbdppdka@@+   .::=wdbp==@@=b:            .@b-qb@d  :d     ..          -mqbbdkaookp+:..:m*@@@=:.      +wd-    : m:@q@h@@@@%d@@%@@@@k  @@      :mbhp=        ..                        
             wo=         .:=p@k=-=mpbbp=.ma=@akw+=: .-+wpddd@@k@h@M  :@=   .+.....:.   :wbdpw@wm=:  .=wa@@@@m#@q=-              : m.@w@M@@@@W@@@@@@@@M+ @@   mpp+.     .:::                             
           m%w          ..+w:=@@obbdq=:mk+  *@pmm@Wpm=:    +@mpbd@=  d@   .Mp...-d-:-mdaw:q:k*+qpkW@@@@@@@@@qw@a+=              . m:Mq%@@@@@@@@@@km@@#q d@:       -++-.                                 
          bd      -: ..-pp@= .:a@@@@M@@@kqm@q   @-         b@@@@@@m-m@o...b@:..=@q.-p%p:+@qq@@@@@@@@@@@@@@@@d:@@m+.             :.+:hqa@@@@W@@@@@@-*@k  @@   :==-                                       
         m@  -....b-.:m@@@b  =w=@*@-       hm  .@o..:-=+mwq%@@@@W@@dk@@wqp@*-==Wa:-q@w=@@a*@@haaM@@@@@@@@@@@d.@@m+-             :.+-hp*@@@@o@@@@@b:@o= @@q                                              
         @q .d:..:*-:-h@@d .+kp=@d*    .:--d@+-m=k*M@@@W@@@d@. :.:M@b@@pdh@%wah@mqb#mm@@@*m=@Ma*@@@@@@@@@@@@q.@@mm=.            : +-op@@@@@@@@@@p+@@a+ p@+         ...                                  
         @p -o+.:-ad+q@a: :maa-@@@@pwqpbkbpqwW#*@M**ahh.bp@ @q .---mpb@@kq@@kpk@+pp=q@@@@@b @%o#@@@@@@@@@@@om.@@mm=:            - m-@d@*@@@@@@@@@@@@*: b@    :++-       :--.                            
         w@=m*%mwdh@Ma@.-+p*b=%@obpm=:       q+ @%bqp@= bpW m@  =++wwmmp*@@@@#@@@pm*@@@bwmw@@MWW@@@@@@@@@@@b-=@%mm=-           .-.q=@d@h@@@@@@@@@@@W: p@-        :=m+-.                                 
          d@bb@@hkhho@@qmmm+qa-              +: +@=+dh-+a@k  @a -mmwppdpqqqppdbbaMWoko@@@@@%M#W@@@@@@@@@@@oq b@bm+=-           -:=mpaa@a@@@@b@@@oqh. *@+    :+mm=.    .:--.                             
           -hak@@@%*M@@@@@@@=                .+  @k@::=mmm*k :@- qpppppppppppddbbbbbkhhaaoo*W@@@@@@@@@@@@@d-.@@wmm+:          :=.m=@p@b@@@@am@@@qp*w .@m  :.    .-mwm=.                                 
                     d@b@@@@@=                b  q@@=  m@@k@  m@  kkkbbbbbbbbbbkkkkhaaaao*M#@@@@@@@@@@@@@am h@dwm++.     =    ===+w*a@d@@Wbq@@@dh@d  Wo    .-=+=-.                                      
                      b@mp@@@@@@@@@@@q        w:  @M   -kk@awm-%@. aMaaahhkhhhhhhhaaaao**%@@@@@@@@@@@@@@aw w@hwmm+=   ::w=   -=:w=@d@b@@@@@@@@@@a: q@p  :=:         ..                                  
                       =@bwb@@@@@@@@@@b        h  dq   =*q@pm+mwk@= b@M*ooaahhaaoo***MW%@@@@@@@@@@@@@@@om w@*mwm+=:        .-m:m=khMMW@@@@@@@@bd. q@b         .:.                                       
                         +hah*@@@@@@@@=         h p+  .w#p@pqqqqwk@d +%@@@@@@%@@@@@@@@@@@@@@@@@@@@@@@@*= b@bwqqwqm-       .-m=+wqWh@b@@@@@ba@pm- =@o     .:.                                            
                            -mqpkhdq=            @@%qwp*W@@Mqqdddqq@@m.wW@@@@@@@@@@@@@@@@@@@@@@@@@@@@d.-@@aW@#ahhkkhad-  .-++=qwMb@d@@*@%da@bm: k@p       ...     ..                                    
                                                =dw: :q@@k=pd.  .-+wk@@w:=k@@@@@@@@@@@@@@@@@@@@@@@%d++%@@b+.      .:+b@a==++=qw*p@b@@hkaM@@p:  p@+   .::.     ..                                        
                                   :+qdbkhaoabd@d:whm   q@@:-ap       :k@b=-mk@@@@@@@@@@@@@@@@@#bwmb@@q        ...:+dbk@am++pm*d@a@@@@@@@a:   @@:       :::.                                            
                              -wdddbbko#@@@@@@@@@@@@@o  =q@@m =hm        m*@d+-=+mpkao*oahbpw+-=w#@k.        ....-qhaomh%++qwWk#o@@@%k@@d  +@@q                                                         
                           +bpm=+qbW@@@@@@@@@@@@@@@@@@  =pb@dp- =a+        :wo@@Wkpwm++++mwqdh@@@h         ....-mko*p:w@pqdd#h@akM@%*@km  @@d                                                           
                        -kd=:=qh@@@@@*pm=-----=+mpo@@@- -hw@@qwq: +a+         :+qkoW@@@@@@@Wak@@.        ....:+k*aw.:o@bkhkah@kd@@@@h=  p@h            .     .::.                                       
                      =@q..ma@@@@*m.    .:---:.    .-@. -*m@@@*+mm. wa-          .-=+mmwwqqqq@@        ..:::+dod=.=a@#hoao*@@M@@@km: .k@h       .:.      :-:       ...                                  
                     Wh  +k@@@@m   -wbkkdqm+p@o@@obmm@  +Mm@@@@@b=++  pa:            .:-=+++h@        ..::=bhm:-d@@@Mhh*%@@@@@@am:.=W@p             :::.    .:--:.                                      
                   m@+  mh@@@m  -qbw:       md.#@@=m@#  bbh@@@@@@@p=m+ .ka=                 @*      ..:::+bm=q@@@@Waho@@@@@kpm=.=d@@h                   .=+:                                            
                  aW. :qo@@a. -kq           @:+%Mp  am .%q@mm#@@@@@@q=w= :oMm-.             %#     ..:::-pqp@@@@@@@@@@@Wbqmm+wk@@@@@@@@hm             :.                  ..                            
                 @b .=b%@@p .dk        .   +% dhM   @  mop@- :q@@@@o*@m+w- -@o+-===-:..     q@. ....:::--wa#q=p@@@@@Mdmmda%@@@@@oaaao#@@@@@q       :.              .:-:.                                
            =   @b .=h%@@p -*=          -  @-.odd  +o .kpW@@w .=@@@@:.*%++q- +@am+++===++====%@: .::::---=maWa+:k@@@*#@@@@@@@k+*p+mm+---+k@@@k.               .:::                                      
           w   k*..-h*@@d =@      :       -@ woa.  @: +Mdw m@M  =a@@@: :*a=mq: q@@kpqwwmmm++mma@q  .----===qh*%b w@@@@@@@@q+h@d=aq  .qpbq-:m@@@h         .::.     .::                                   
           d  =@:::d#@@o.:@        +     -@= abk  .@  dkW    @@  =h@@@   :*d-mm  q@@%*akkbbbdddk@@+  .-====+daoWo:@mo@@@@+mk  hk-+.     .ha= m@@@+    ..    .:-:                                        
       .  q:  @+.:-@@@@-:%q         --   =@:+*b:  *+ -Mph     @@  =M@@@    =*q-mm  k@@@@@@@W@@@@@@@@p:  .:=+qkao%@h =@bp@@-    q*-+:      .Ma..d@@b     .                                               
       b  *  m@.::b@@@b.m%   ..       +  ahphbk   @  pka.      @b .=@@@b     m*+-w= .a@@@*         .@@@dm-:-mh@@h+..m@bqq@@     +%--+   :   m@- +@@%                      ...                           
      =q =q  @w:-=@@@@=:M:     .-.     m=a.a**.  pk =Mpo       .@: -+@@@.     .@#=-w- -@@          +@m@M@@p=-:    :q%kaha-@@+    q@m=+ =     .@w =@@M     .::.     .:-:.                                
      k: k:  @-:mq@@@@-=@         .-    @W+*ab   @  poab        q@  =o@@%      @w%a==w- ma:  -+mwww@=wkh@@km=:..=mmwqk**a:@@qwq.  =aq-q-   -   @q m@@h        :==-.    :-:.                             
      @  @  m@:-wa@@@k-q%            ::q@+@@a   pk =@dW          @- -+@@@.     p=.k@b-+w: p@*m+++=p@:a@o-         .+dh%@q-@pmbmm+.  bb-p  =     @: q@@m  .--:    :-:.                                   
      @  @  hW-=w*@@@q:bb              @oMk@@.dd@  k@oq          ba  =@@@p      p :p#@p-+w:.pow+mw%bp@:          :+da@%d+d@p. mdwww  bb=dk  .   :@ :o@@     .:-.      ..                                
      @  M  %a-+q#@@@w-kp             +@d@km=%m=k q@k@           :@  =h@@@       m -ph@@q=mw.-k@- @p@           -wk@@hp+dpkkpm. +bwqm:op=h+      Mw m@@b         .-.                                    
      o  a  ao-mq@@@@q-bd             -kqp   pp=@dkh@=            @  =q@@@        = :dh@@@q=wm:=kW@d@         -wb*Mkdm+d.  -abdd  paqa@@m+@      .@ .o@@                                                
      m  d  w@:qp@@@@h=qo              @q@dph*@@@@@b.             @  =+@@@         +-=b@km@@dmpm.b@w@d. ..:=+qbkbpqm+d@bmwwmqbddkqpdda*amd*p      @  q@@.                     .                         
         +  .@=qd#@@@@++@               @@@@d- w=:               .@  =m@@@       .+b*ph@q+qo@kbqp@-=h@kpqqpdbbpq+=mdhdqpppbkkkkhkkka%@@%kdw       o- q@@=              ..                               
         .:  @dqdh@@@@w-@=            -: =m..   - -              m@  -p@@@     wb=     @q-wdM d@mhm+:b@dwmwqqqpdo@@@@@@hkpw+=--=d*@@apw           o- q@@+         .:.     .:::            ..            
          .  p@mkh@@@@o=m@        .-.   =- m  . m  =   .:        @q  -@@@%    Ww       d@.mm@+ q@h@*k#@@@@p+=:h@@@@@@qa     .==:--::: -.          %. p@@:     :-.     =oop+==+p*@w      bm =@           
              @hk%@@@@@m-Wd     -.     m.  m  -  q  .=    :.     @  :=@@@w    @        -@m-wq@pmqbpp@@mqq@     @dW@@@d*w=+-       + - - -  .      @ .k@@  ::        +@q         :k@m    @+:q-           
              =@h@#@@@@@--@- ..      .q   q   +  m:   m      .  ab  :b@@@     M*==mm+++m*@--+w#w   da=q+@:     p*hW@@@b%      -  .: + .  +   .   +* m@@W    .:.    p@             +@p                   
               h@*#@@@@@k:=@-       ++    d   w   h    =+      w@  .=@@@M      @@==mwqwwmk@m-==++wwm+mm%=     -w@@@@@@@wb    :   w  w  m  =      @. k@@: .::     :=@            .. q@                   
                @@*@@@@@@d:=@:     q.    m.   p   .d     q     @-  :%@@@.       okq+==+mmqk@*q++mmmwd%@h+mm=-.  :@dd#@@@wb      -   w  ..  -:   oq +@@a  ..   =km=p@.           .. -@                   
                 @@#@@@@@@k--Wm  .w      b    p    q-     +- .@=  :k@@@k          :qo@@@*kdpwh@Mbkkbq=           -@pd%@@@+o-    +   m   m   .: pb +@@@       .@     +          ... kk                   
                  @@M@@@@@@M=:dhm-      :-    q     a       k@:  :b@@@@                .:=mqqw-                   :@dpM@@@+wq  .    +    :   :Ww +@@@:       .@    .        ......qa mmmp               
                   o@kW@@@@@@w:+@d      q     m     :w     k*   -o@@@@                                              ohqa@@@b+qqw    =    -  mb: p@@@. .=m+kq-b- :.      ...::.. .+mp@.  @  :wq          
                    w@oh@@@@@@a=-mab-   -     =      w   do:  -q@@@@@    .-:                                         m@bd*@@@d+wpm- w    +pq=.q@@@@-:===   bd:.    .......::-mm=:   @=:w.    w          
                      W@k*@@@@@@k+-+dopk-     .      +@kp.  :q@@@@@a   ==   -==+pp                                     d@hdM@@@@bqwwqqqwm=+qo@@@@a-::::..=+.    ...........  ...+q++-                   
                       =@@bo@@@@@@Wq=-=wdbbpqwbbwqddp+.  :+d@@@@@@+  =+.  =d=..  @d                                      qahkh@@@@@@@@@@@@@@@@@d=.:===-=:.  .........::---===+++==+=-==++=--::.         
                         m@#bh@@@@@@@Mdm=-:----:::...:=qa@@@@@@@a  :-   pd-   -pd@:  +w-:bM                                 mpkkhW@@@@@@@@@@d+:::=====++mqpdbho*******akbdpqwm+-:..                     
                           =M%hko@@@@@@@@@WabdppdbhM@@@@@@@@@@@q:-:.:whb.       .@. -b   b#                     ..:::--=++++md@@@@@@@@@@@@@@%@@@Moaakbpqwmm=-:.                                         
                              wWWhk*@@@@@@@@@@@@@@@@@@@@@@@@aw::=+m+-.     ..   +w=mqwqqqm-+qpbhaoM%@@@@@@@@@@@%#WM*oahhkbdppqwm++=--:..                                                                
                                 +dkkka*@@@@@@@@@@@@@@@@Wbm==+wqqqqqqpdbkho*%@@@@@@@@@@@@@%Mohbdpqm+=--::..                                                                                             
                                .:-mp@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%Mohbdpqm+=--:.                                                                                                                       
                           =wppkkhhkbdpppppqqwwm+==-:..                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
`;
