export const ascii = `
                                                                       =q                                                 =dakpqqdhkm                                                                   
                                                                     :ad@@                              .-+wqpbhbdpppp+:w@k.      :ma@%=                                                                
                                                                   =hw.b@k                        :mpdpq+-     .   :-=-:mo@boMhpm=mqbM*@@                                                               
                                                                 .*=  a@@                     +dbw-              .     ::    mpwh@@@@@@kd@                                                              
                                                                 @.  +@ho                  wad-         :     .=.    :w: ...w- :.d+p#@@@da@                                                             
                                                                *a  -@b@                +kp:   .m=:-==pp---::m-  ...=q..::.w+ :--h-mmoao@@@.                                                            
                                                               dM .a@k@m              p@hqqdoM@@@aoahh@*oMW%@@*#okpka--:::mq ---+b-mmbahh@@@m                                                           
                                                              q@  m%b@:            .p@@a*p=.  :               +:-md*@@@MkbW-----pw=mmbhh**#@@@q                                                         
                                                             w@  +oq@.         :pkWp:        :      .-       +        =qp%@@#bwma++mmkkho*M%@*@@+                                                       
                                                            w@  +aq@.       :bam  :    -    :. .  ..+  .....m: ...... m    :mo@@@adqwhha*%W@@@*M@%                                                      
                                                           q@  =hw@.      m@qw   -    m  . .= .....+: .....-m .......=p ::.   -.mW@@@@**W@%@@@%Mk@@.                        .:::.                       
                                                          q@  =a+@.     .@q     -. . -= ...+. ..::-w ..::::q..:::::..d.::::::+=   :-d@@@@@@@@@@%Mdo@=                    +o@@bqm+wdkp:                  
                                                         w@  =am@.     =@:  :   w ...p..::=d-=++++qq=====-mw ::::::.w+.::::::q:-=m+=::q@@@@@@@@@@odq@=                   @-   :+qm:.+k@q                
                                                        q@  =hm@:     -@:  =   =m -=m@qpkaW@a**MMM@@oooooa@apwm+=-:-d:---:::=+:==w=mwwqp.+a@@@@@@@@qq@.                  =@      :qd+:-d@p              
                                                       w@  =h+@:      @:   m -=b#k*W#@@o***@%kkhhkb@akkhhh@@*MMM*okadm=-----q-==wmmmwwhpdpmpoo@@@@@@+k@                   w@       .qh+:+M@.            
                                                      m@  =km@:      hh . =hqhM@@@ooW@@@@@@@@@@@@@@@@@@@@@@@oakkbbk@MWobpwmwm=++w+mmmqkmbkk@bm+@@@@%p:@p      pdh*k        p@        :hd=mb@w           
                                                     m@  =km@.       @. wmk@@**%@@@@@@@@*oakbddpppdppbkaoW@@@@@@@@@@hbkh*MW#kpmq+mmmmbqpbba*h%bMwd@@o:+@    m@@+-mo@.       ko         b*mqd@m          
                                                    +@  =h+@.       m@ :@hkh@@@@@@@adw+===--::...+==+---=+mwqqpbhM@@@@@@ak*hoo*Wbpqwqhwbbb*ba*a@owm@@a.@=  -@  @mmwd@=       @d         komqp@.         
                                                   m@  =h+@.        k@dpa@@@@@@@%q+=-:.          . :       .:--==+mwqbk@@@@@WhbhW%ok*pdkkkodoaa@oMho=*@@d  @:   @+wwd@m       @-         @dwmo%         
                                                  m@  =k+@.         *aWok%@@kdkd=-:.               .              .-=++-q@%@@@@*db*@@Wohk*bhahMooo*Mh+d@@  @    .@+qqp@m     +@.         m@mmw@         
                                                 m@  =k+@.          kWq@@@@=mp+::.                        q@@@@@@k+  :--.=hhh@@@@@@ako%%%#kahoohoo*ka*+doop*     =@+pqp@d -h*m           .@m++@-        
                                                +@  +k+@.           .@@*@@ +p+.:   :wa@@h-               b@@@@@@@@@@p  ::..dbdM@@@@@@Wo*M%#oa@a**aobaabh.d@k      +@wkk@@am              .@m-=@:        
                                =wmmqm         +@  +bm@              m@@@ -qm.:  +o@@@@@@@                mdho@@@@@@@@- .:. pppa@@@@@@@@ohW@@%W*o*khokkM*.@@       w@hp:                 :@=-w@         
                              dd.   :W@bwbpdapp@  mkm@                d@ :w+.. -@@@@@@#ap                        :wo@@@: ..  qqph@@@@@@@@@@kk#@M*akaadoaM=W@                             do--@p         
                            .@-    -@a-p@k   @@  mkm@                 @: mm.. m@@b=.                                 :q:  ..  pwp*@@@@@@@@@@@ha#@#*adboahwd@p             =b-           =@-:b@          
                            @:    :%@   +@d.  bkk@w@d                @p +w.   :.                                           .. :pwd@@@@@@@@@@@@@*da%odaaoq*-m@         -b@@@@@m         +@m.q@           
                           =@   .-m@@w-   q@%m-q*@@bh@.             m@ -q- .                               .wkahq-         ... +qwb@@@@@@@@@@@@@@bo@@oodqW w@@     =@@@@@q@m @m       d@w:q@.           
                           +@=-:-+wk@@aw-  .mo@@@obq.m@             @. mm .      =bM*b-                  =@@hm+wd%@+         .  wwqo@@@@@@@k#@@@@@@bqMoqW= @.=@    d@@bq@ q@:d@w    m@*@=q@-            
                       .+mmh@%kdqqpd@@*@Wkpm=-+qk@@@W@@q           Md =q       =@@q==mhW                d@+  =bhbqw@%           :qwd@@@@@@@k=k@@@@@@*p@@q q@  :@-    a@ a@ @@a@@m.qhq:whq@b             
                     wh=    .q@@obkk@@wk@@@@%okbdkhah-m@.         -@ .q-      p@=  w*odpo              w@    .p@@@@+h%           +wpo@@@@@@@*q@@@@%k@@@W+-@:    bh    +@q@@@@@@@@::   dba@=             
                    hb         w@@@@@+ =qbM@@@@@@@@@@q @:         @= +w      m@.    *@@@W.             @       %@@@@=@=       .  .qwb@@@@@@@@W@@@@@bq@@md@+       kk:  .@@@@h+.       mkh@m             
                    @           -@@@q  .+qdkW@@@@@@adp#q         m@ -q:      @:     -@@@@+            ww       @@@@@a=a      ..  .mwpo@@@@%W@@@@@@a@mw@@@:          do-  :            :ow@h             
                  :k@bw-         +@@q+=+wpdba@@@hmo@@h:          @: mw      md      @@@@@p            w  =w. +@@@@@@@.b       .. .-qqb@@@@@**@@@@@@@@.b@.             ka       .=pkb-  W+@@             
               md=.  -d@am-..   .qd@hmwpdbko%@@@Wdm-:-ph        qo =q:      b. m@w:@@@@@@p            .  h@% .@@@@@@@ -       ..  .mwdW@@@@@@@@@@@@@@m @@              -@    +M@@hdo@= qpo@.            
              ow        d@aqm==mp+k@ow+pdko@@@@q       kh       @  wm .     m  h@b:@@@@@@+               b@@@@@@@@@@@          .. :-qpa@@@@@@@%kb@@@om  @h              -@  +@oq    +@ .aq@p            
             =@          w@@ahkpmh@@km=pdba@@@+    .- +@       bk +p.          b@@@@@@@@@                :@@@@@@@@@@q          .. .:qqb@@@@@@@@%ph@W@b+ +@=              %+ +@h-     M. h=W@            
             q@-=-:      :b@@@@@@@@od=+pdk*@@#:=::-+:+@        @ .w+ .         :@@@@@@W@p                 k@@@@@@q@@           ..  :+qpo@@@@@@@@@@@+=**  k@              :@  @km     +p mqq@-           
             -@pdbpq+:..:ww@@@@@@@@@=+mpbh%@@amm==++ @:       *p +d..           q@**@ohd                   b@bbahaq            ... ..qqb@@@@@*w+@@Wo+:@m  @@              @  dkb      %  *+@h           
              @*a@@*bdpppwq@@@#pbh@k-wpbo@@@@@qqmmm- @       -@ .p= .            -Wadq:                     .qqm-               ..  .wwd@@@@@@%qm@@o*+d@m .@w             wp :ob.     k= bma@           
              .@@@@@@@@#%@@@@kmmwaa wdk@@@@@@@dqwww. @       @m mw .                                                +h@@h:      ... .mqpa@@@@@%Wd@@@odM@kk m@              @  Wk+     -o -d+@w          
              .@ddp*@dWhhh@@p++wah mdk@#M@@o@@kqqwq  @      w@ -d:        .mp+.                                   =h@@@@%@:     ...  -wwb@@@@@@@@@@@@@@@=md #@             W. dhd      %. k:a@          
             .@mpqpW +:  m%==+wah mpd@@o@@@w@@kqqqw da      @. m+ .       p@@@h=                             -wa@@Mq@@@h         ..  .+wda@@@@@@@ao@@@@@@+@: @m            +k :ok:     qq mmm@-         
             @bpdq@ -   -@.-+woh mpp@@oM@@m@@hdppq -@      *d mq .        -  @@@@hdm-.                :=wbo@@Mbm=::d@@@          ... .=ppd@@@@@@@@bo@@@@@@m+.m@             @  *dm     :% .h-**         
            #obdd@:=.  -@--mwoa mpp@@oMW@+W@hdpdw +@      =@ -p:             q@@@m+qba*MM*oaaao*M%@@@@Whpm=:.    -M@@@p           ..  =qqph@@@@@@@@M@@@@@@h m @@            *: ddb      W: k-d@         
           =@bkh@-m-  -@==mqa* mpp@%aM*@+a@addp- b*       @: w+ :             @@@@w                          .-mo@@@@@                =+qqd@@@@@@@@@@pw%@@@p+ =@m           =k :oa.     wk =q=@m        
           *@@@@-w+. -@q+qpa@.mpd@@hMo@+k@*kd= +@=       @q +w .              +@@@@@=                     :mk@@@@@@@@              .. :+wqpk@@@@@@@@@aw:#@@@W+ q@            @  obw     .@  *:h@        
          hq ab=q=..=@dmpd*@-wbb%@oWa@+k@Md+:mMw        p@ -w. .               m@@@@@@@d+:          .=wk@@@@@@@@@@@%       +=      ... mmqqp@@@@@@@@@%@dm@@@@%= @@           k= mbk      o= d+q@:       
         p@   pw  .:%@mdk%@=qkh%@oWa@mb@*bdk@o         -@  q- :                 +@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@p       .pp      ... -mwqqk@@@@@@@@@@Wo@@@q+%..@q          :W  od-     +% -p=#h       
         @q      ::+@pba@@mda*@@*Wo@mb@Wk*@=@=         @m m+ :      .            :@@@@@@@@@@@@@@@@@%bqmmmmwdba@@@:                  ... ++qqp@@@@@@@do@@@@@@@.w* q@           @  hpq      @: k-d@       
         W@=:  ..::q@o*@@qhM#@@M#*@wk@Whkbw qb        oh +p .     mpp.             k@@@@@@@@hqmmm+---==+===wh@@+                    ...  +wppk@@@@@@b=+@@@km@@pdd @@          dm +bk      qd mwm@q      
         @khhm-:.:+qa%hm+a%@@@WW@@mo@Mhkkw:. Mw      +@ -p- .     pw:                k@@@@pm+-:::.-====++q*@o=                      .... .mqpq@@@@@@@@wq@@@w:#@MW +@=         .@  *pm     :@ .k=h@      
         hd.mW*pmmmqdddb*M@@@@@@#m%@Mahkb=::  mkq-   @: qm .                           =a@@adqwmmwqqpbhW%k+                          .... :qqpd@@@@@@@Wp@@@@pbqk@  @@          @  bqd      *= b-q@:     
         .@==-p@@akbbkaoM@@@@@Mpq@@*aahhq-:::.  .mda@p +q :                                -mqdbbbdpw+:                              ...:. wqdp@@@@@@@@@@@@@@@*d@p =@w         qq -kb:     +o -p:@b     
          m@=qqmb@@@@W#@@@@@@%pd@@*oaahhp-------:. d@ =q:..                                                                           :.:: .pqkk@@@@@@@@@@@@@@@@@@= @@          @  abw     .@  o:b@     
           -@dqhhkM@@@@@@@@@k+-@@doMoaahkw=-------m@. qm :                                                                            ..::. qqdd@@@@d.    .=q*@@@@W +@+         M= mkb      hm q+w@m    
             m**hao%@@@@@kqd@#d+@@wqa*oaakpm++===+@a +p..                                                                              ..:: -qqb#@@+            -p@@d@@         =M  *d=     =@ :b:o@    
               .wbkhkbpqmmqd+    m@owmph***akkkbb#@.:pm .                                 .:::..                                       ...:. qqbk@M                 -p@b.        @  hdd      W= b:p@:   
                    .:-:.          -k#kqwqbaM#@@@@o mb::                           -wbo*oakbbbkaoW#od+.                                 ...: +pdb@@+..                 .qoq      om +kh.     mk =p=*b   
                                      -paokdpdbk@@: qq .                       .q@@b+.            .-mk@@k+.                             ...-.:dqb*@apm=::......           =*d    :@  *d+     .@  *-d@   
                                          :+phoo@@ =p:..                     mW*m      ..:---===+mwmm==+b@@k=                              := qqkk@@abbpqm=-::......   ..:. m@=   @  hqp      M= b=m@=  
                                                @d qb :                    p@w      ...    :-====+mppdkkdqq#@W+                            :+ mqdk@@@@hkkkkdqm+-::... ....:m+-@w  a+ mbh:     +h =d-o%  
                                                @::dw :                  m@+        ..     :====++++qpphW@#dq@@a=                          .+ -qpko@@@@@Mbppppppb-.......::=aw=@: =# .%hm     .%  W-d@  
                                               m@ +b-.:                 Mb          .... ..-====+++++pdda@@@@dd@@m:                        .+.:pqkb@@@@@@@@@%ka@. .....:::-+h*:@k  @  hpa:    :k  dwq@p 
                                               aW wd.:.               -@+          .......:=====+++++wbddM@@@@op@@p=.                      .=:.dwhd@@@@@@@@@@@@  .....:::--paM:**  hm :omkdwpkp   :a-W@:
                                               @q pp -               =@-          .......:=====++++m+mbbdk@@@@@@p@@d+:                     .=:.dmkd@@@@@@@@@@d  .....:::--mh*h @d  :@  .-..    .=m=@qmp@
                                               @= pp -              :@=         ........-=====++++mmmmdbkk@@@@@@#q@@dm.                    .=:.pmkb@@@@@@@@M.   ....:::--+ko@--@    @.           .p@poq=
                                               @::dq.-              @d .-..:::. .:::::-======mmmmmmmmmdkkkM@@@@@@hq@@qm.                   .=..qmhk@@@@@@q      ...:::--mh*@q @p    *q   =dp@dqkp  =@=@k
                                               @:-dq.:.            p@  =   -=-:::::::-=====+mmmmmmmmmwkkhk*@@@@@@@db@@mm                   .= -qwoh@@@@m       ...:::-=qaM@m @o     @.  db=oo   :M: ma+o
                                               @.-dq.::            @w -=   ==-------======+mmmmmmmmmmphhh**@@@@@@@om@@pm+                  .- +mpoa@@@         ..:::-+doWo=-@d      @  -@==@d     @  @=p
                                               @:-dp.::  .        +@  +++++=============+mmmmmmmmwwmqhaaa@@@@@@@@@@wd@*+m:                 :- mmda@@@         ...::=wh*aw-b@-       @- .@+mq@+    W: kmq
                                               @-.dd.::  .        b@ =m++++++++++===+++mmmmmmmmwwwwwkooo*@@@@@@@@@@qm@@mm+                 =:.qmbh@@       .....:-mdkbm=p@w         .@  wommq@@m -d  W:k
                                               @m bb:::           @@ wmmmmm++++++++++mmmmmmmmmwwwwwko***@@@@@@@@@@@p+@@wmm.               .= -qqhk@b      .....:-mpppd*@@m           +M  .pdpqp#@m  q==@
                                               @k db=.:.          @% dqmmmwmmmmmmmmmmmmmmmmmwwqqwqk**MW%@@@@@@@@@@@p=@@qmm-               -- mwpaM@+    . ....::-=qaM@@%@d            .om   .::.   qwm@+
                                               p@ qdw.::          %@:bdpqwwwwwwwwwwwwwmmmmwqqqqqph**MW#@@@@@@@@@@@@d+@@qmm=              .=:.pwhk@@w    .......::-+pkdk@@@:phha@b       -bd+:...=q#Wd+  
                                               :@.-pd.::          d@-kbbdpqqqwwwwwwwwwqqpqqqqqpb*MMWW#@@@@@@@@@@@@#p+@@wmm=              == =ppMk@@*:.........:::--mkaq@@@@k--==@W         .=+mmm-      
                                                @d pb=::.         =@+dokkbddpqqqqqqqpppppqqqpboMMW#%@@@@@@@@@@@@@@*wq@%wmm=             -=- pqa*%@@@w-.......::::--=bad@@@@:-=mq+@                      
                                                d@ mdd:::  .       @h=@*hkbbbddddppppqqpppbhoMW#%@@@@@@@@@@@@@@@@@o+M@bwmm-            .== -dq@h@@@@@q+::::::::::--=bb@@@*q-=+kq+@                      
                                                 @+ dh=:::         d@=b@%*hkkkkbbbbbbbkhaoMW#@@@@@@@@@@@@@@@@@@@@@qm@@qwmm.            ==: qwkMM@@@@@#dq+-::::::---=mqpm=-==mh*:Wq                      
                                                 h@ wbb.::.         @@-@@@@%WMM**MMMMW#%%@@@@@@@@@@@@@@@@@@@@@o@oa-@@dwmm+            ==- mpp@k@@@@@@@@kdpw+=----=====--=+wd*h=ko                       
                                                  @w kam.::  .      :@k=@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@*@k*:k@hwwm+. :         -=- -dw%a@@@@@@@@@@Mbdbdpqwwwwwqppdko*hw+%d                        
                                                  q@.wbh-.::         -@b+@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@M#k*.q@*wwmm++kad       -=-..pwh%*@@@@@@@@@@@@%kddddbkhhaaakbpqqoa.                         
                        .::                        @@.dkh::..         -@M+o@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@*Wbbb.p@*wwwmwk*ao+      ===. qqb@h@@@@@@@@@@@@@@@@@#okpdbbbbhaabm                            
                   ==  :=m   d        . .-.         @h:khb:: .         .@@wp@@@@@@@@@@@@@@@@@@@@@@@@@@@@%okqd+.%@hwwwmmkWMa=     .===. ppb@h@@@@@@h@@@@@@@@@bk@+d@@mmm=:                                
                   @.  p@@h   %  .:.::=++w=         -@q=hhp:-            q@Wmp@@@@@@@@@@@@@@@@@@@@@@@@@odqq+:q@@pwwwmm::w=      :++=. pqb@h@@@@@@@p%@@@w%@@@q@m %@                                      
                   k        . @::=qmm::              +@qmhhp:-  .         :@@*qdo@@@@@@@@@@@@@@@@@@%Wakdw=-p@@bwwwwmm-         =++=. ppb@a@@@@@@%bM@@@hm@@@ha: @@                                       
                   b   :+:+w .W                       m@pwhaq.=.            q%@@hqdk*@@@@@@@@@@@@Wohpw+=mo@@kqwwwwww-        .+mm=.:ppk@h@@@@@@@W@@@@@*@W%@:  @@                                        
                    +d-:b:mww+                         +@kqhhp-=-            =qb@@@#kpqwqpppdppqwm++wk@@@*dqwqwwwww:        -mm+-.=dph@a@@@@@@@@@@@@@@@*-*: -@b                                         
                     @-mk%ka=                           :@Wwhkb+-=.           :mwwpkW@@@@@W****W@@@@@Wkpqqqqqqwwwm.       :+mm=--mppMMM@@@@@@@@@@@@wM@@qh. q@+                                          
                     %   kqb.                             @@wbhkw-=-.           =mmmmwqpdbkkkkbbdpqwwwwqqqqqqqqw=       -+mm+::mqwd@*@@@@@@@@@@@@@%@@@@d  @@            +=:...-:m                       
                     a- -*mk.                              k@pqkkd+---.           =mwwwwwwwwwwwwwwwwqqqqqqqqqw=       -mmmm-:mpqpM@W@@@@@@@o@@@@@@@*qW. m@q            :M-  h@M. q                      
                     a: =@mb                                =@#wdkbq=--:            -+mwwwwwwwwwwqqqqqqqqqw=.      .=mmmm=-mbppa@W@@@@@W*MWa:%@@@@@m- .@%           ::mq. w  pa=  d                     
                     a: =k=a.                                 h@bqkkdq+--:.            :=+mmwwqqqqwwwwm+-.      .=+mmm+==wdpd*@#M@@@@@*hkka*p.@@@@w .h@-     :+.=:- -:.:-  q:   +a-                     
                     pm =h=k                                   o@@ddhbdpm=---:               .......      ..:-=+++++==mpddbM@Mh@@@@@@ap+++qho=m@k.:a@+      q:w p p-hw%w@mm+a%dpmp                      
                      .:=+-                 .:.-.              k%@@@bbhkbpw=----:.                     ..:-==++++++mqddba##M*@@@@@@aaw----=qah @ho@=        pwpphbakdqm+---=pm.                         
                                   p m=++d=p-m+mq+             bq-*@@@kbkkbpqm+=-----::..       ....::--==+++++mwpppbh*%M*@@@@@@@@@@q=-:---+b*++@+           wdd.                                       
                                   +mdqhkababhkbp              =k qd@@@@Mbbhkbbdqm+=----======+++++mm+===++mqpdddbh*W**@@@@@@W@@@@@@k=:::--+phk @                         .::..                         
                                                                @.=+da%@@@@ohhaakbddpqqwmmm+++++mmwmmmwqqppdbkh*WM*W@@@@@@@@@@@@@@W@@+-:---+qba.*b                                                      
                                                           :=+wp@bmmmda**h@@@@@ahhahhkkkbdppppppddbbdkhao**MW##@@@@@@@oo@@@M@@@@@%aa@q-----=mda+m@-::::....                                             
                                           ..::---=====-=doq-    .-mpdho*m@h+pa@@@@@Moahkkkhaooooooaaaaaaa*@@@@@@@@@@aa@@@@#Wabqqd*@@b---==+mqhd:@m==========+=========--::.                            
                                    .-===========-=-=--+@b       .:+qbha*md@====mqh@@@@@@@@@@@@@@@@@@@@@@@@@@@@*b*@@@obdqqqpba@@@@hd@bm+++mqdhoa.@q-=============================-:.                    
                                  ---------====--------@@:....::-=wdhaahh++@m=+++===+wpkW@@@@@@@W*oohkkbkkdpdMkdppqqqph%@@@@@adq+=+@o:     .:+bb:@a================================+++=------::::::..   
                                    ..::::-------------@@dqwwqqpdbkhhaahka@@+++++++++====++wpbaM@@@@@@@@@@@@@@@@@@@@@Wabpwm+===+++@a      .--=qa=q@+===============================-:::-::::::::..      
                                             .::-------+*@@@@@@@@@@@@@%M*adm+++++=================++mmwqqqqqqqqwmm++=======+++++=m@mm=-::--=+wk*m+@m=======================--:.                         
                                                         .-==+++++==---::------========================================+++++++++++@@pwmmmwqpbkkpd@*=+++=======---:..                                    
                                                                                   ......:::::::::---------------------------------d%@%M*oo*W@@@Mw=-                                                    
                                                                                                                                        .:::.                                                           
                                                                                                                                                                                                        
                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
`;
